name: main

on:
  push:
    branches:
      - main

jobs:
  stage:
    runs-on: ubuntu-latest
    steps:
      - name: wake up ghost
        run: curl -I ${{ secrets.GHOST_ADMIN_API_URL }}/ghost/
      - name: Repository Dispatch Build - Main
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GHA_TOKEN }}
          event-type: build-production
          client-payload: '{"ref": "${{ github.ref }}", "url": "${{ secrets.DEPLOY_HOST }}"}'
